### ISSUE TITLE
crash on main menu

### ISSUE THREAD

**Issue by Nep-Soundfont** [AllwineDesigns/SerialCraftMod#1]
the game crashes on the main menu after installing, i'm using the 0.4 version and i also tried 0.3 please help (oh, and maybe update the mod, I like the concept)[heres my log, apparently it doesnt recognise jssc as a mod](https://github.com/AllwineDesigns/SerialCraftMod/files/3244064/fml-client-latest.log)

**Comment by jallwine** [comment]
Can you try it without any other mods? My guess is it’s a conflict with one of your other installed mods. The jssc.jar file isn’t a mod, so that’s fine. It’s just a library that’s needed for using the Serial port.

**Comment by Nep-Soundfont** [comment]
okay, thanks, it works now, just a conflict with bspkrs' core (the crash was at the main menu)
